//
//  PokemonDetailWorker.swift
//  SPokemon
//
//  Created by José Moreira on 20/12/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Domain
import RxSwift

class PokemonDetailWorker: BaseWorker {

    func fetchPokemonList(id: String) -> Single<PokemonDetailModel> {
        return dataManager.fetchPokemonDetail(id: id)
    }
}
