//
//  IntroInteractor.swift
//  SPokemon
//
//  Created by José Moreira on 20/12/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntroBusinessLogic: BaseBusinessLogic {
    func fetchData(request: PokemonList.Something.Request)
}

protocol IntroDataStore
{
    //var name: String { get set }
}

class PokemonListInteractor: BaseInteractor, IntroBusinessLogic, IntroDataStore {
    var presenter: IntroPresentationLogic?
    var worker: PokemonListWorker?

    override func basePresenter() -> BasePresentationLogic? { return presenter }


    func fetchData(request: PokemonList.Something.Request) {
        worker = PokemonListWorker()

        worker?.doSomeWork().subscribe(onSuccess: { model in
            print(model)
        }, onError: { error in
            print(error)
        }).disposed(by: disposeBag)
    }
}
