//
//  IntroRouter.swift
//  SPokemon
//
//  Created by José Moreira on 20/12/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol IntroRoutingLogic {
    func showPokemonDetail()
}

protocol IntroDataPassing {
    var dataStore: PokemonListDataStore? { get }
}

class PokemonListRouter: NSObject, IntroRoutingLogic, IntroDataPassing {
    weak var viewController: PokemonListViewController?
    var dataStore: PokemonListDataStore?

    // MARK: Routing

    func showPokemonDetail() {

        let destinationVC = PokemonDetailViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation

    func navigateToSomewhere(source: PokemonListViewController, destination: PokemonDetailViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }

    // MARK: Passing data
    func passDataToSomewhere(source: PokemonListDataStore, destination: inout PokemonDetailDataStore) {
        destination.selectedPokemon = source.selectedPokemon
    }
}
