//
//  IntroPresenter.swift
//  SPokemon
//
//  Created by José Moreira on 20/12/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PokemonListPresentationLogic: BasePresentationLogic {
    func presentPokemonList(response: PokemonList.List.Response)
    func presentPokemonDetail(response: PokemonList.SelectedPokemon.Response)
}

class PokemonListPresenter: BasePresenter, PokemonListPresentationLogic {
    weak var viewController: PokemonListDisplayLogic?

    override func baseViewController() -> BaseDisplayLogic? { return viewController }

    func presentPokemonList(response: PokemonList.List.Response) {
        let tableSection = PokemonList.TableSection(title: PokemonList.SectionItem.pokemon,
                                                    items: response.pokemonList.map { PokemonList.TableItem.pokemon(name: $0.name,
                                                                                                                    imageUrl: getImageUrl(with: $0.url))})
        let viewModel = PokemonList.List.ViewModel(pokemonList: tableSection, title: "Pokemon list")
        viewController?.displayPokemonList(viewModel: viewModel)
    }

    func presentPokemonDetail(response: PokemonList.SelectedPokemon.Response) {
        let viewModel = PokemonList.SelectedPokemon.ViewModel()
        viewController?.displayPokemonDetail(viewModel: viewModel)
    }

    private func getImageUrl(with url: String) -> String {
        if let id = url.split(separator: "/").last {
            return "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/\(id).png"
        } else {
            return ""
        }
    }
}


